server:
  port: 8080

bitjita:
  base-url: https://bitjita.com
  app-identifier: CraftBoard Projet-DAN2026

craftboard:
  app-admin-password: ${CRAFTBOARD_APP_ADMIN_PASSWORD:DestroyTown53}

spring:
  datasource:
    url: ${CRAFTBOARD_DB_URL:jdbc:mariadb://209.222.101.116:25383/craftboard}
    username: craftuser
    password: mdp123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
